--------------------------------------------------------
--  DDL for Sequence SEQ_USER_ENTITY
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_USER_ENTITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEQ_AUTHORIZATION_ENTITY
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_AUTHORIZATION_ENTITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Sequence SEQ_PAYMENT
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_PAYMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;



create table USER_ENTITY
(
	ID NUMBER(19,0) PRIMARY KEY NOT NULL,
	CUSTOMER_ID VARCHAR(255) NOT NULL,
	LOGIN VARCHAR(255) NOT NULL
);

create table AUTHORIZATION_ENTITY
(
	ID NUMBER(19,0) PRIMARY KEY NOT NULL,
	ACCESS_TOKEN CLOB NOT NULL,
	AUTHORIZATION_ID VARCHAR(255) NOT NULL,
	OPERATION_ID VARCHAR(255) NOT NULL,
	OPERATION_TYPE VARCHAR(255) NOT NULL,
	TPP_NAME VARCHAR(255) NOT NULL,
	USER_ID NUMBER(19,0),
	CONSTRAINT  FK_AUTHORIZATION_ENTITY foreign key ("USER_ID") references USER_ENTITY("ID")
);

create table PAYMENT
(
	ID NUMBER(19,0) PRIMARY KEY NOT NULL,
	DISPOSITION_ID VARCHAR(255) NOT NULL,
	PAYMENT_ID VARCHAR(255),
	AUTHORIZATION_ENTITY_ID NUMBER(19,0),
	CONSTRAINT  FK_PAYMENT FOREIGN KEY ("AUTHORIZATION_ENTITY_ID") references AUTHORIZATION_ENTITY("ID")

);











